# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
 repositories:
   - repository: R1
     type: GitHub
     endpoint: MyGithubConnection
     name: jainamanjain/Repo1

jobs:
 - job: J1
   pool:
    name: default
   steps:
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact1'
         ArtifactName: 'A1'
         publishLocation: 'Container'
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact2'
         ArtifactName: 'A2'
         publishLocation: 'Container'
      - powershell: |
            ls $(Build.ArtifactStagingDirectory)/
 - job: J3
   pool:
    name: default
   steps:
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact3'
         ArtifactName: 'A3'
         publishLocation: 'Container'